sudo: required
services:
  - docker

before_install:
  - docker build -t brifer/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run brifer/react-test npm test -- --coverage

after_success:
  - docker build -t brifer/multi-client ./client
  - docker build -t brifer/multi-nginx ./nginx
  - docker build -f ./gosrc/Dockerfile.Server -t brifer/multi-server ./gosrc
  - docker build -f ./gosrc/Dockerfile.Worker -t brifer/multi-worker ./gosrc
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push brifer/multi-client
  - docker push brifer/multi-nginx
  - docker push brifer/multi-server
  - docker push brifer/multi-worker