version: '3'
services:
  postgres:
    image: 'postgres:latest'
  redis:
    image: 'redis:latest'
  nginx:
    restart: always
    depends_on:
      - client
      - api
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - 8080:80
  api:
    depends_on:
      - redis
      - postgres
    restart: on-failure
    build:
      context: ./gosrc
      dockerfile: Dockerfile.ServerDev
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./client:/app

  worker:
    depends_on:
      - redis
    restart: on-failure
    build:
      context: ./gosrc
      dockerfile: Dockerfile.WorkerDev
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379